version: "3.3"
services:
  db:
    image: postgres:${POSTGRES_DB_VERSION}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back_net
  app:
    build: .
    image: rhinock/wms:${APP_VERSION}
    networks:
      - front_net
      - back_net
    environment:
      ConnectionStrings__WmsDbContextPostgres: "Host=db;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    ports:
      - "${APP_PORT}:80"
volumes:
  db-data:

networks:
  back_net:
  front_net:
