version: "3.3"
services:
  postgres:
    image: postgres:${POSTGRES_DB_VERSION}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./db-data:/var/lib/postgresql/data
    # ports:
    #   - 5432
  app:
    build: .
    image: rhinock/wms:${APP_VERSION}
    environment:
      ConnectionStrings__WmsDbContextPostgres: "Host=postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=postgres;Password=${POSTGRES_PASSWORD}"
    ports:
      - "${APP_PORT}:80"
volumes:
  db-data:
