apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres-service
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
