apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  type: {{ .Values.service.type }}
  selector:
    app: wms
