// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WMS.DataAccess.Data;

namespace WMS.DataAccess.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    partial class WmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WMS.DataAccess.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "pencil",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 2L,
                            Name = "pen",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 3L,
                            Name = "felt-tip pen",
                            Price = 30.00m
                        });
                });

            modelBuilder.Entity("WMS.DataAccess.Models.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("MaximumItems")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MaximumItems = 100L,
                            Name = "miniature"
                        },
                        new
                        {
                            Id = 2L,
                            MaximumItems = 10000L,
                            Name = "decent"
                        },
                        new
                        {
                            Id = 3L,
                            MaximumItems = 1000000L,
                            Name = "hefty"
                        });
                });

            modelBuilder.Entity("WMS.DataAccess.Models.WarehouseItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("WarehouseId", "ItemId")
                        .IsUnique();

                    b.ToTable("WarehouseItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Count = 50L,
                            ItemId = 1L,
                            WarehouseId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Count = 5000L,
                            ItemId = 2L,
                            WarehouseId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Count = 500000L,
                            ItemId = 3L,
                            WarehouseId = 3L
                        });
                });

            modelBuilder.Entity("WMS.DataAccess.Models.WarehouseItem", b =>
                {
                    b.HasOne("WMS.DataAccess.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.DataAccess.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
